httplug:
    plugins:
        logger: ~
    clients:
        my_guzzle6:
            factory: 'httplug.factory.guzzle6'
            plugins: 
                - 'httplug.plugin.logger'
                - 'httplug.plugin.redirect'
            config:
                timeout: 3
        my_curl:
            factory: 'httplug.factory.curl'
            plugins: 
                - 'httplug.plugin.logger'
                - 'httplug.plugin.redirect'
            config:
                CURLOPT_CONNECTTIMEOUT: 3
                CURLOPT_SSL_VERIFYPEER: 0
                CURLOPT_SSL_VERIFYHOST: 0
