cron_backend_startnow:
    path:     /bbcron/startjobnow
    defaults: 
        _controller: BugBusterCronBundle:Backend:startJobNow
        _scope: backend
        _token_check: true

cron_frontend_startjobs:
    path:     /bbcron/startjobs
    defaults: 
        _controller: BugBusterCronBundle:Frontend:startJobs
        _scope: frontend
        _token_check: false
